class Constants {
  static const double PIZZAPADDING = 40;
  static const double HEADERHEIGHT = 200;

  static const List<String> BREADS = [
    'assets/Bread/Bread_1.png',
    'assets/Bread/Bread_2.png',
    'assets/Bread/Bread_3.png',
    'assets/Bread/Bread_4.png',
    'assets/Bread/Bread_5.png',
  ];
  static const List<String> BASIL = [
    'assets/Basil/Basil_1.png',
    'assets/Basil/Basil_2.png',
    'assets/Basil/Basil_3.png',
    'assets/Basil/Basil_4.png',
    'assets/Basil/Basil_5.png',
    'assets/Basil/Basil_6.png',
    'assets/Basil/Basil_7.png',
    'assets/Basil/Basil_8.png',
    'assets/Basil/Basil_9.png',
    'assets/Basil/Basil_10.png',
    'assets/Basil/Basil_11.png',
  ];
  static const List<String> BROCCOLI = [
    'assets/Broccoli/Broccoli_1.png',
    'assets/Broccoli/Broccoli_2.png',
    'assets/Broccoli/Broccoli_3.png',
    'assets/Broccoli/Broccoli_4.png',
    'assets/Broccoli/Broccoli_5.png',
    'assets/Broccoli/Broccoli_6.png',
    'assets/Broccoli/Broccoli_7.png',
    'assets/Broccoli/Broccoli_8.png',
    'assets/Broccoli/Broccoli_9.png',
    'assets/Broccoli/Broccoli_10.png',
    'assets/Broccoli/Broccoli_11.png',
  ];
  static const List<String> MASHROOM = [
    'assets/Mushroom/Mushroom_1.png',
    'assets/Mushroom/Mushroom_2.png',
    'assets/Mushroom/Mushroom_3.png',
    'assets/Mushroom/Mushroom_4.png',
    'assets/Mushroom/Mushroom_5.png',
    'assets/Mushroom/Mushroom_6.png',
    'assets/Mushroom/Mushroom_7.png',
    'assets/Mushroom/Mushroom_8.png',
    'assets/Mushroom/Mushroom_9.png',
    'assets/Mushroom/Mushroom_10.png',
    'assets/Mushroom/Mushroom_11.png',
    'assets/Mushroom/Mushroom_12.png',
  ];
  static const List<String> ONION = [
    'assets/Onion/Onion_1.png',
    'assets/Onion/Onion_2.png',
    'assets/Onion/Onion_3.png',
    'assets/Onion/Onion_4.png',
    'assets/Onion/Onion_5.png',
    'assets/Onion/Onion_6.png',
    'assets/Onion/Onion_7.png',
    'assets/Onion/Onion_8.png',
    'assets/Onion/Onion_9.png',
    'assets/Onion/Onion_10.png',
    'assets/Onion/Onion_11.png',
    'assets/Onion/Onion_12.png',
    'assets/Onion/Onion_13.png',
  ];
  static const List<String> SAUSAGE = [
    'assets/Sausage/Sausage_1.png',
    'assets/Sausage/Sausage_2.png',
    'assets/Sausage/Sausage_3.png',
    'assets/Sausage/Sausage_4.png',
    'assets/Sausage/Sausage_5.png',
    'assets/Sausage/Sausage_6.png',
    'assets/Sausage/Sausage_7.png',
    'assets/Sausage/Sausage_8.png',
    'assets/Sausage/Sausage_9.png',
    'assets/Sausage/Sausage_10.png',
    'assets/Sausage/Sausage_11.png',
    'assets/Sausage/Sausage_12.png',
    'assets/Sausage/Sausage_13.png',
    'assets/Sausage/Sausage_14.png',
    'assets/Sausage/Sausage_15.png',
    'assets/Sausage/Sausage_16.png',
    'assets/Sausage/Sausage_17.png',
    'assets/Sausage/Sausage_18.png',
    'assets/Sausage/Sausage_19.png',
    'assets/Sausage/Sausage_20.png',
    'assets/Sausage/Sausage_21.png',
    'assets/Sausage/Sausage_22.png',
    'assets/Sausage/Sausage_23.png',
    'assets/Sausage/Sausage_24.png',
  ];
}
